### PR TITLE
Use Documenter 0.25

### LINKED ISSUE #45: Update Documenter.jl

### PR DESCRIPTION
**Pull request by mortenpi**
Bump Documenter to the upcoming 0.24 (currently pinned to the `mp/katjax` branch with `docs/Manifest.toml`).

The LaTeX definitions can now be done in `make.jl` (JuliaDocs/Documenter.jl#1097), so no need to load the `latex.js` (which was a bit unreliable, since we were actually loading and configuring MathJax twice).

Here is a demo: https://mortenpi.eu/gsoc2019-mockups/bulma/v14/AtomicLevels/

Once merged, will fix #45.

### CODE REVIEW

**Comment by mortenpi** [comment]
There are some docs issues, but the upgrade to 0.25 looks smooth. @jagot did you figure out if we need MathJax (in other repos), or whether KaTeX is sufficient?

**Comment by jagot** [comment]
KaTeX is not sufficient in other repos (don't remember exactly, but I think I could not get eqrefs and such things to work), so I think our conclusion was to use MathJax everywhere, to be consistent.

What are the "docs issues"?

**Comment by mortenpi** [comment]
Alright, I'll change this over to MathJax then before we merge.

> What are the "docs issues"?

Doctests not passing, `parse` included in two places, some bad at-refs. I.e. all the build warnings.

**Comment by mortenpi** [comment]
> Alright, I'll change this over to MathJax then before we merge.

Scratch that, it already is using MathJax :laughing: So I this say this is good to go.

**Comment by jagot** [comment]
Thanks!

**Pull request merged**
