### PR TITLE
Remove Compat as a dependency

### PR DESCRIPTION
**Pull request by mortenpi**
Tests pass, so I don't think we rely on anything from Compat. Close #79.

### CODE REVIEW

**Comment by jagot** [comment]
We needed it for `isnothing` @ Julia 1.0, but since we've dropped Julia < 1.2, we can drop Compat.jl.

**Comment by jagot** [comment]
I never understood if the package should be a dependency of the docs or not?

**Comment by mortenpi** [comment]
Since we have the Manifest at the moment, it should be.

**Comment by jagot** [comment]
Fair enough :)

**Pull request merged**
